version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - export LANG=en_US.UTF-8
      - aws codecommit get-commit --repository-name emma-maintenance-scripts --commit-id $CODEBUILD_RESOLVED_SOURCE_VERSION
      - pip3 install pipenv
      - pipenv run python -m pip install --upgrade pip
      - pipenv install -d
      - mkdir -p integration-reports
      - mkdir -p test-reports
      - mkdir -p deploy
  build:
    commands:
      - pipenv run python make.py test all
      - pipenv run python make.py package all int
      - pipenv run python make.py deploy all int
      - pipenv run python make.py integration all int
      - pipenv run python make.py upload_s3 all int
    on-failure: ABORT

reports:
  integration-report:
    files:
      - 'TESTS-*.xml'
    base-directory: 'integration-reports'
    discard-paths: yes
    file-format: "JUNITXML"
  test-report:
    files:
      - 'junit-*.xml'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: "JUNITXML"
