version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - export LANG=en_US.UTF-8
      - aws codecommit get-commit --repository-name emma-search-ingest --commit-id $CODEBUILD_RESOLVED_SOURCE_VERSION
      - pip3 install pipenv
      - pipenv run python -m pip install --upgrade pip
      - cd api/lambda
      - pipenv install -d
      - mkdir -p integration-reports
      - mkdir -p deploy
  build:
    commands:
      - pipenv run python make.py deploy_s3 all qa
      - pipenv run python make.py integration all qa
    on-failure: ABORT

reports:
  integration-report:
    files:
      - 'TESTS-*.xml'
    base-directory: 'api/lambda/integration-reports'
    discard-paths: yes
    file-format: "JUNITXML"

