openapi: 3.0.0
info:
  description: API for submitting metadata to the EMMA Federated Search Index
  version: 0.0.6
  title: EMMA Federated Index Ingestion API
  contact:
    email: bookshare-developers@benetech.org
  license:
    name: TBD
tags:
  - name: ingestion
    description: Operations on metadata submitted to EMMA federated search index
paths:
  /records:
    put:
      tags:
        - ingestion
      summary: Inserts or updates metadata records in the search index
      operationId: upsertRecords
      description:
        Inserts, or updates one or more metadataRecords in the search index.  For the
        upsert operation, if no such record exists for the emma_repository, emma_repositoryRecordId,
        dc_format, and emma_formatVersion, a record is created.  Otherwise the existing record is updated. 
        emma_formatVersion is optional.  The number
        of records to be updated at once is capped at 1000.
      responses:
        "202":
          description: Items accepted for update.
        "207":
          description: Some items inserted or updated
          content:
            application/json:
              schema:
                description: List of errors, mapped to the numbered metadata record in the order received
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                description: List of errors, mapped to the numbered metadata record in the order received
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IngestionRecordList"
        description: Ingestion metadata record
  /recordGets:
    post:
      tags:
        - ingestion
      summary: Retrieves metadata records in the search index
      operationId: getRecords
      description:
        Retrieves one or more metadataRecords in the search index.   
        Records are uniquely identified by the emma_repository, emma_repositoryRecordId,
        dc_format, and emma_formatVersion.  emma_formatVersion is optional.  The number
        of records to be retrieved at once is capped at 1000.
      responses:
        "200":
          description: Items retrieved
          content:
            application/json:
              schema:
                description: May be returned by upsert operation.  List of errors, mapped to the numbered metadata record in the order received
                type: array
                items:
                  $ref: "#/components/schemas/MetadataRecord"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                description: List of errors, mapped to the numbered metadata record in the order received
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentifierRecordList"
        description: Metadata identifier record
  /recordDeletes:
    post:
      tags:
        - ingestion
      summary: Deletes metadata records in the search index
      operationId: deleteRecords
      description:
        Deletes one or more metadataRecords in the search index. Records are uniquely identified by the emma_repository, emma_repositoryRecordId,
        dc_format, and emma_formatVersion.  emma_formatVersion is optional.   The number
        of records to be deleted at once is capped at 1000.
      responses:
        "202":
          description: Items accepted for deletion.
          content:
            application/json:
              schema:
                description: If applicable, a list of "not found" records that could not be deleted will appear in the result body.  Otherwise the result body will be empty.
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
        "207":
          description: Some items deleted
          content:
            application/json:
              schema:
                description: May be returned by upsert or delete operation.  List of errors, mapped to the numbered metadata record in the order received
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                description: List of errors, mapped to the numbered metadata record in the order received
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentifierRecordList"
        description: Metadata identifier record
components:
  schemas:
    IngestionRecordList:
      title: Metadata ingestion record list request
      description: List of metadata ingestion records
      type: array
      items:
        $ref: "#/components/schemas/IngestionRecord"      
    IdentifierRecordList:
      title: List of identifier records
      description: List of metadata record identifiers
      type: array
      items:
        $ref: "#/components/schemas/IdentifierRecord"
    IngestionRecord:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/IngestionRecord
    IdentifierRecord:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/IdentifierRecord
    MetadataRecord:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/MetadataRecord
    MetadataCommonRecord:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/MetadataCommonRecord
    EmmaRecordIdentifier:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/EmmaRecordIdentifier
    EmmaRepository:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/EmmaRepository
    EmmaRepositoryRecordId:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/EmmaRepositoryRecordId
    EmmaFormatVersion:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/EmmaFormatVersion
    DublinCoreFormat:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/DublinCoreFormat
    PublicationIdentifier:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/PublicationIdentifier
    PeriodicalIdentifier:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/PeriodicalIdentifier
    RemediationFields:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/RemediationFields
    PeriodicalFields:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/PeriodicalFields
    SchemaOrgFields:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/SchemaOrgFields
    EmmaCommonFields:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/EmmaCommonFields
    DublinCoreFields:
      $ref: ../shared/model/common-domain-0.0.6.schema.yaml#/components/schemas/DublinCoreFields