---
components:
  schemas:
    DublinCoreFormat:
      description: '[Format](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/format/)
        of this instance of the work.'
      enum:
      - brf
      - daisy
      - daisyAudio
      - epub
      - braille
      - pdf
      - grayscalePdf
      - word
      - tactile
      - kurzweil
      - rtf
      type: string
    EmmaFormatVersion:
      description: Version of the format used by this instance of this work
      type: string
    EmmaRecordIdentifier:
      description: The unique identifier for a metadata record within the EMMA Federated
        Search Index.  Not guaranteed to have any particular format.
      title: EMMA metadata record identifier
      type: string
    EmmaRepository:
      description: Identifier for a repository
      enum:
      - bookshare
      - hathiTrust
      - internetArchive
      - emma
      type: string
    EmmaRepositoryRecordId:
      description: The unique identifier for a work within a repository
      type: string
    IdentifierRecord:
      description: Schema to identify a single metadata record in the EMMA Federated
        Search index, for deleting or retrieval, for example.
      oneOf:
      - properties:
          emma_recordId:
            $ref: '#/components/schemas/EmmaRecordIdentifier'
        required:
        - emma_recordId
      - properties:
          dc_format:
            $ref: '#/components/schemas/DublinCoreFormat'
          emma_formatVersion:
            $ref: '#/components/schemas/EmmaFormatVersion'
          emma_repository:
            $ref: '#/components/schemas/EmmaRepository'
          emma_repositoryRecordId:
            $ref: '#/components/schemas/EmmaRepositoryRecordId'
        required:
        - emma_repository
        - emma_repositoryRecordId
        - dc_format
      title: Metadata to uniquely identify a record in the EMMA Federated Search Index
      type: object
    IdentifierRecordList:
      description: List of metadata record identifiers
      items:
        $ref: '#/components/schemas/IdentifierRecord'
      title: List of identifier records
      type: array
    IngestionRecord:
      allOf:
      - $ref: '#/components/schemas/MetadataCommonRecord'
      description: Schema for JSON metadata records to be submitted to the EMMA Federated
        Search Index ingestion service.
      required:
      - emma_repository
      - emma_repositoryRecordId
      - emma_retrievalLink
      - dc_title
      - dc_format
      title: Metadata ingestion schema for EMMA Federated Search Index
      type: object
    IngestionRecordList:
      description: List of metadata ingestion records
      items:
        $ref: '#/components/schemas/IngestionRecord'
      title: Metadata ingestion record list request
      type: array
    MetadataCommonRecord:
      properties:
        dc_creator:
          description: The [creators](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/creator/)
            of the work
          items:
            type: string
          type: array
        dc_description:
          description: '[Description](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/description/) of the work; typically a synopsis'
          type: string
        dc_format:
          $ref: '#/components/schemas/DublinCoreFormat'
        dc_identifier:
          description: A standard [identifier](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/identifier/)
            for a work
          items:
            $ref: '#/components/schemas/PublicationIdentifier'
          type: array
        dc_language:
          items:
            description: Code for the [language](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/language/)
              of the work, using the [ISO 639-2 3-character code](https://www.loc.gov/standards/iso639-2/php/code_list.php).
            pattern: ^[a-z]{3}$
            type: string
          type: array
        dc_publisher:
          description: The name of the [publisher](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/publisher/)
          type: string
        dc_relation:
          description: List of standard [identifiers](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/relation/)
            for related works
          items:
            $ref: '#/components/schemas/PublicationIdentifier'
          type: array
        dc_rights:
          description: Ownership-based [usage rights](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/rights/)
            on the work
          enum:
          - publicDomain
          - creativeCommons
          - copyright
          - other
          type: string
        dc_subject:
          description: A [subject](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/subject/)
            describing the work
          items:
            type: string
          type: array
        dc_title:
          description: The [title](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/title/)
            of the work
          type: string
        dc_type:
          description: '[Type](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/type/)
            of this instance of the work'
          enum:
          - text
          - sound
          - collection
          - dataset
          - event
          - image
          - interactiveResource
          - service
          - physicalObject
          - stillImage
          - movingImage
          type: string
        dcterms_dateAccepted:
          description: '[Date](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/dateAccepted/)
            that the work was accepted into the repository, using [ISO-8601](https://www.iso.org/iso-8601-date-and-time-format.html)
            format (YYYY-MM-DD)'
          format: date
          type: string
        dcterms_dateCopyright:
          description: The 4-digit year that the work was copyrighted
          pattern: ^[0-9]{4}$
          type: string
        emma_collection:
          description: A set of works within a repository
          items:
            type: string
          type: array
        emma_formatFeature:
          description: Feature of the format used by this instance of this work
          items:
            enum:
            - tts
            - human
            - grade1
            - grade2
            - nemeth
            - technical
            - ueb
            - ebae
            - literary
            - music
            type: string
          type: array
        emma_formatVersion:
          $ref: '#/components/schemas/EmmaFormatVersion'
        emma_lastRemediationDate:
          description: Last date that this work was remediated
          format: date
          type: string
        emma_lastRemediationNote:
          description: Note regarding the last remediation on this work
          type: string
        emma_repository:
          $ref: '#/components/schemas/EmmaRepository'
        emma_repositoryUpdateDate:
          description: Date that this metadata was last updated in the source repository
          format: date
          type: string
        emma_repositoryRecordId:
          $ref: '#/components/schemas/EmmaRepositoryRecordId'
        emma_retrievalLink:
          description: Link to download an actual work from a repository
          format: uri
          type: string
        emma_sortDate:
          description: Last date that the work or this index was updated, guaranteeing
            a non-null value. If available, this defaults to the same value as last
            remediation date.  If not available, it defaults to date accepted.  If
            date accepted is not available, it defaults to the date that the record
            was last updated in this index. The value of sort date is determined at
            indexing time, and does not need to be sent through the ingestion API.
          format: date
          type: string
        emma_webPageLink:
          description: Link to a web page which describes a work from a repository
          format: uri
          type: string
        s_accessMode:
          description: How the user can perceive this instance of the work as described
            in the schema.org [Access Mode specification](https://www.w3.org/wiki/WebSchemas/Accessibility#Accessibility_terms_.28Version_2.0.29).
          items:
            enum:
            - auditory
            - chartOnVisual
            - chemOnVisual
            - colorDependent
            - diagramOnVisual
            - mathOnVisual
            - musicOnVisual
            - tactile
            - textOnVisual
            - textual
            - visual
            type: string
          type: array
        s_accessModeSufficient:
          description: A list of single or combined access modes that are sufficient
            to understand all the intellectual content of a resource as described
            in the schema.org [Access Mode Sufficient specification](https://www.w3.org/wiki/WebSchemas/Accessibility#Accessibility_terms_.28Version_2.0.29)
          items:
            enum:
            - auditory
            - tactile
            - textual
            - visual
            type: string
          type: array
        s_accessibilityAPI:
          description: Accessibility APIs of this instance as derived from to the
            schema.org [Accessibility API specification](https://www.w3.org/wiki/WebSchemas/Accessibility#Accessibility_terms_.28Version_2.0.29).
          items:
            enum:
            - ARIA
            type: string
          type: array
        s_accessibilityControl:
          description: Accessibility controls of this instance derived from to the
            schema.org [Accessibility Control specification](https://www.w3.org/wiki/WebSchemas/Accessibility#Accessibility_terms_.28Version_2.0.29).
          items:
            enum:
            - fullAudioControl
            - fullKeyboardControl
            - fullMouseControl
            - fullTouchControl
            - fullVideoControl
            - fullSwitchControl
            - fullVoiceControl
            type: string
          type: array
        s_accessibilityFeature:
          description: Accessibility features of this instance derived from to the
            schema.org [Accessibility Feature specification](https://www.w3.org/wiki/WebSchemas/Accessibility#Accessibility_terms_.28Version_2.0.29).
          items:
            enum:
            - alternativeText
            - annotations
            - audioDescription
            - bookmarks
            - braille
            - captions
            - ChemML
            - describedMath
            - displayTransformability
            - displayTransformability/background-color
            - displayTransformability/color
            - displayTransformability/font-height
            - displayTransformability/font-size
            - displayTransformability/line-height
            - displayTransformability/word-spacing
            - highContrastAudio
            - highContrastDisplay
            - index
            - largePrint
            - latex
            - longDescription
            - MathML
            - physicalObject
            - printPageNumbers
            - readingOrder
            - rubyAnnotations
            - signLanguage
            - sound
            - stillImage
            - structuralNavigation
            - synchronizedAudioText
            - tableOfContents
            - tactileGraphic
            - tactileObject
            - taggedPDF
            - timingControl
            - transcript
            - ttsMarkup
            - unlocked
            type: string
          type: array
        s_accessibilityHazard:
          description: Accessibility hazards of this instance as derived from to the
            schema.org [Accessibility Hazard specification](https://www.w3.org/wiki/WebSchemas/Accessibility#Accessibility_terms_.28Version_2.0.29).
          items:
            enum:
            - flashing
            - noFlashingHazard
            - motionSimulation
            - noMotionSimulationHazard
            - sound
            - noSoundHazard
            type: string
          type: array
        s_accessibilitySummary:
          description: Human-readable summary of accessibility features or deficiencies
            of this instance of the work as described in the schema.org [Accessibility
            Summary specification](https://www.w3.org/wiki/WebSchemas/Accessibility#Accessibility_terms_.28Version_2.0.29)
          type: string
      type: object
    MetadataRecord:
      allOf:
      - properties:
          emma_recordId:
            $ref: '#/components/schemas/EmmaRecordIdentifier'
          emma_titleId:
            description: The unique identifier for a work within the EMMA Federated
              Search Index
            type: string
      - $ref: '#/components/schemas/MetadataCommonRecord'
      - required:
        - emma_recordId
      description: Schema for JSON documents which are retrieved from the EMMA Federated
        Search Index ingestion service.
      title: Metadata record schema for EMMA Federated Search Index
      type: object
    PublicationIdentifier:
      description: The lowercase scheme and identifier for a publication.  For example,
        isbn:97800110001. Only alphanumeric characters are accepted. No spaces or
        other symbols are accepted. Dashes will be stripped from the stored identifier.
        Accepted schemes are ISBN, ISSN, LCCN, UPC, and OCLC.
      pattern: ^((isbn|upc|issn):[0-9Xx\-]{8,17}|lccn:[a-zA-Z0-9]{1,12}|oclc:[0-9]{1,14})$
      title: Publication Identifier
      type: string
info:
  contact:
    email: bookshare-developers@benetech.org
  description: API for submitting metadata to the EMMA Federated Search Index
  license:
    name: TBD
  title: EMMA Federated Index Ingestion API
  version: 0.0.4
openapi: 3.0.0
paths:
  /recordDeletes:
    post:
      description: Deletes one or more metadataRecords in the search index. Records
        are uniquely identified by the emma_repository, emma_repositoryRecordId, dc_format,
        and emma_formatVersion.  emma_formatVersion is optional.   The number of records
        to be deleted at once is capped at 1000.
      operationId: deleteRecords
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentifierRecordList'
        description: Metadata identifier record
      responses:
        '202':
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    type: string
                  type: array
                description: If applicable, a list of "not found" records that could
                  not be deleted will appear in the result body.  Otherwise the result
                  body will be empty.
                type: object
          description: Items accepted for deletion.
        '207':
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    type: string
                  type: array
                description: May be returned by upsert or delete operation.  List
                  of errors, mapped to the numbered metadata record in the order received
                type: object
          description: Some items deleted
        '400':
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    type: string
                  type: array
                description: List of errors, mapped to the numbered metadata record
                  in the order received
                type: object
          description: Invalid input
      summary: Deletes metadata records in the search index
      tags:
      - ingestion
  /recordGets:
    post:
      description: Retrieves one or more metadataRecords in the search index. Records
        are uniquely identified by the emma_repository, emma_repositoryRecordId, dc_format,
        and emma_formatVersion.  emma_formatVersion is optional.  The number of records
        to be retrieved at once is capped at 1000.
      operationId: getRecords
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentifierRecordList'
        description: Metadata identifier record
      responses:
        '200':
          content:
            application/json:
              schema:
                description: May be returned by upsert operation.  List of errors,
                  mapped to the numbered metadata record in the order received
                items:
                  $ref: '#/components/schemas/MetadataRecord'
                type: array
          description: Items retrieved
        '400':
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    type: string
                  type: array
                description: List of errors, mapped to the numbered metadata record
                  in the order received
                type: object
          description: Invalid input
      summary: Retrieves metadata records in the search index
      tags:
      - ingestion
  /records:
    put:
      description: Inserts, or updates one or more metadataRecords in the search index.  For
        the upsert operation, if no such record exists for the emma_repository, emma_repositoryRecordId,
        dc_format, and emma_formatVersion, a record is created.  Otherwise the existing
        record is updated. emma_formatVersion is optional.  The number of records
        to be updated at once is capped at 1000.
      operationId: upsertRecords
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestionRecordList'
        description: Ingestion metadata record
      responses:
        '202':
          description: Items accepted for update.
        '207':
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    type: string
                  type: array
                description: List of errors, mapped to the numbered metadata record
                  in the order received
                type: object
          description: Some items inserted or updated
        '400':
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    type: string
                  type: array
                description: List of errors, mapped to the numbered metadata record
                  in the order received
                type: object
          description: Invalid input
      summary: Inserts or updates metadata records in the search index
      tags:
      - ingestion
tags:
- description: Operations on metadata submitted to EMMA federated search index
  name: ingestion
