
ITEM_URL = 'https://hdl.handle.net/2027/'

MAX_STRING_LENGTH = 1024

IMPRINT_REGEX_PATTERN = r'''^(.*[A-Za-z])[^A-Za-z]+([\d]{4})'''
ISBN_TRAIL_REGEX_PATTERN = r'([0-9Xx\-]{9,13}).*'
OCLC_LCCN_TRAIL_REGEX_PATTERN = r'([a-zA-Z]{0,3}[0-9]{1,14})[^0-9]*'
ISSN_TRAIL_REGEX_PATTERN = r'([0-9]{4}-[0-9]{3}[0-9xX]).*'
STD_ID_VALIDATION_PATTERN = r"^((isbn|upc|issn):[0-9Xx]{8,14}|lccn:[a-zA-Z0-9]{1,12}|oclc:[0-9]{1,14})$"

FIELD_NAMES = ['htid',
               'access',
               'rights',
               'ht_bib_key',
               'description',
               'source',
               'source_bib_num',
               'oclc_num',
               'isbn',
               'issn',
               'lccn',
               'title',
               'imprint',
               'rights_reason_code',
               'rights_timestamp',
               'us_gov_doc_flag',
               'rights_date_used',
               'pub_place',
               'lang',
               'bib_fmt',
               'collection_code',
               'content_provider_code',
               'responsible_entity_code',
               'digitization_agent_code',
               'access_profile_code',
               'author']



RIGHTS_MAP = {
    'pd': 'publicDomain',
    'ic': 'copyright',
    'op': 'copyright',
    'orph': 'copyright',
    'ic-world': 'copyright',
    'pdus': 'other',
    'cc-by-3.0': 'creativeCommons',
    'cc-by-nd-3.0': 'creativeCommons',
    'cc-by-nc-nd-3.0': 'creativeCommons',
    'cc-by-nc-3.0': 'creativeCommons',
    'cc-by-nc-sa-3.0': 'creativeCommons',
    'cc-by-sa-3.0': 'creativeCommons',
    'orphcand': 'copyright',
    'cc-zero': 'creativeCommons',
    'icus': 'copyright',
    'cc-by-4.0': 'creativeCommons',
    'cc-by-nd-4.0': 'creativeCommons',
    'cc-by-nc-nd-4.0': 'creativeCommons',
    'cc-by-nc-4.0': 'creativeCommons',
    'cc-by-nc-sa-4.0': 'creativeCommons',
    'cc-by-sa-4.0': 'creativeCommons',
    'pd-pvt': 'other'
}

INSTITUTION_MAP = {
    'allegheny': 'Allegheny College',
    'amherst': 'Amherst College',
    'archive': 'Internet Archive',
    'arizona': 'University of Arizona',
    'asu': 'Arizona State University',
    'aub': 'American University of Beirut',
    'auburn': 'Auburn University',
    'auckland': 'University of Auckland',
    'augusta': 'Augusta University',
    'baylor': 'Baylor University',
    'bc': 'Boston College',
    'bentley-umich': 'Bentley Historical Library, University of Michigan',
    'berkeley': 'University of California, Berkeley',
    'brandeis': 'Brandeis University',
    'brooklynmuseum': 'Brooklyn Museum',
    'brown': 'Brown University',
    'brynmawr': 'Bryn Mawr College',
    'bu': 'Boston University',
    'bucknell': 'Bucknell University',
    'buffalo': 'University At Buffalo, The State University of New York',
    'byu': 'Brigham Young University',
    'carleton': 'Carleton College',
    'case': 'Case Western Reserve University',
    'cgu': 'Claremont Graduate University',
    'claremont': 'Claremont University Consortium',
    'clarkart': 'Sterling and Francine Clark Art Institute',
    'clements-umich': 'William L. Clements Library, University of Michigan',
    'clemson': 'Clemson University',
    'cmc': 'Claremont McKenna College',
    'cmu': 'Carnegie Mellon University',
    'colby': 'Colby College',
    'colorado': 'University of Colorado Boulder',
    'columbia': 'Columbia University',
    'cornell': 'Cornell University',
    'dartmouth': 'Dartmouth College',
    'depaul': 'DePaul University',
    'dickinson': 'Dickinson College',
    'duke': 'Duke University',
    'elon': 'Elon University',
    'emory': 'Emory University',
    'fau': 'Florida Atlantic University',
    'fiu': 'Florida International University',
    'flbog': 'State University System of Florida',
    'frick': 'The Frick Collection',
    'fsu': 'Florida State University',
    'gatech': 'Georgia Institute of Technology',
    'gc-cuny': 'CUNY Graduate School and University Center',
    'georgetown': 'Georgetown University',
    'getty': 'The Getty Research Institute',
    'gettyshib': 'Getty Research Institute',
    'gmu': 'George Mason University',
    'grinnell': 'Grinnell College',
    'gsu': 'Georgia State University',
    'harvard': 'Harvard University',
    'hathitrust': 'HathiTrust',
    'haverford': 'Haverford College',
    'hawaii': 'University of Hawaii',
    'hmc': 'Harvey Mudd College',
    'ht_private': 'Private Donor',
    'ht_support-microsoft': 'Digitization Support from Microsoft',
    'ias': 'IAS, via Princeton University',
    'iastate': 'Iowa State University',
    'illinois': 'University of Illinois at Urbana-Champaign',
    'iu': 'Indiana University',
    'jhu': 'Johns Hopkins University',
    'keio': 'Keio University',
    'kennesaw': 'Kennesaw State University',
    'knowledgeunlatched': 'Knowledge Unlatched',
    'ksu': 'Kansas State University',
    'ku': 'University of Kansas',
    'lafayette': 'Lafayette College',
    'loc': 'Library of Congress',
    'macalester': 'Macalester College',
    'mcgill': 'McGill University',
    'mcmaster': 'McMaster University',
    'mdanderson': 'University of Texas M.D. Anderson Cancer Center',
    'miami': 'University of Miami',
    'milproj-dc-umich': 'Millennium Project',
    'missouri': 'University of Missouri - Columbia',
    'mit': 'Massachusetts Institute of Technology',
    'mndigital': 'Minnesota Digital Library',
    'mnhs': 'Minnesota Historical Society',
    'monash': 'Monash University',
    'montana': 'Montana State University',
    'msu': 'Michigan State University',
    'mtholyoke': 'Mount Holyoke College',
    'ncl': 'National Central Library',
    'ncsu': 'North Carolina State University',
    'nd': 'University of Notre Dame',
    'neu': 'Northeastern University',
    'nfb': 'National Federation of the Blind',
    'nmsu': 'New Mexico State University - Las Cruces Campus',
    'northwestern': 'Northwestern University',
    'nypl': 'New York Public Library',
    'nyu': 'New York University',
    'okstate': 'Oklahoma State University',
    'olemiss': 'University of Mississippi',
    'osu': 'The Ohio State University',
    'ou': 'University of Oklahoma',
    'pfw': 'Purdue University Fort Wayne',
    'pitt': 'University of Pittsburgh',
    'pomona': 'Pomona College',
    'press-umich': 'University of Michigan Press',
    'princeton': 'Princeton University',
    'psu': 'Pennsylvania State University',
    'purdue': 'Purdue University',
    'queensu': "Queen's University",
    'richmond': 'University of Richmond',
    'rochester': 'University of Rochester',
    'rutgers': 'Rutgers University',
    'scrippscollege': 'Scripps College',
    'smith': 'Smith College',
    'smu': 'Southern Methodist University',
    'stanford': 'Stanford University',
    'swarthmore': 'Swarthmore College',
    'swmed': 'University of Texas Southwestern Medical Center',
    'syr': 'Syracuse University',
    'tamu': 'Texas A&amp;M University',
    'tcu': 'Texas Christian University',
    'technicalreports': 'Technical Report Archive &amp; Image Library',
    'temple': 'Temple University',
    'ttu': 'Texas Tech University',
    'tufts': 'Tufts University',
    'tulane': 'Tulane University',
    'txstate': 'Texas State University - San Marcos',
    'ua': 'University of Alabama',
    'ualberta': 'University of Alberta',
    'ubc': 'University of British Columbia',
    'uc': 'University of Cincinnati',
    'ucalgary': 'University of Calgary',
    'ucdavis': 'University of California, Davis',
    'ucf': 'University of Central Florida',
    'uchicago': 'University of Chicago',
    'uci': 'University of California, Irvine',
    'ucla': 'University of California, Los Angeles',
    'ucm': 'Universidad Complutense de Madrid',
    'ucmerced': 'University of California, Merced',
    'uconn': 'University of Connecticut',
    'ucop': 'University of California, Office of the President',
    'ucr': 'University of California, Riverside',
    'ucsb': 'University of California, Santa Barbara',
    'ucsc': 'University of California, Santa Cruz',
    'ucsd': 'University of California, San Diego',
    'ucsf': 'University of California, San Francisco',
    'udel': 'University of Delaware',
    'ufl': 'University of Florida',
    'uga': 'University of Georgia',
    'uh': 'University of Houston',
    'uic': 'University of Illinois at Chicago',
    'uiowa': 'University of Iowa',
    'uky': 'University of Kentucky',
    'umass': 'University of Massachusetts Amherst',
    'umd': 'University of Maryland, College Park',
    'umdl-umich': 'University of Michigan Library IT, Digital Library Production Service, Digital Conversion Unit',
    'umich': 'University of Michigan',
    'umn': 'University of Minnesota',
    'unc': 'University of North Carolina at Chapel Hill',
    'ung': 'University of North Georgia',
    'union': 'Union College',
    'universityofcalifornia': 'University of California',
    'unl': 'University of Nebraska - Lincoln',
    'unlv': 'University of Nevada - Las Vegas',
    'unm': 'University of New Mexico',
    'unr': 'University of Nevada, Reno',
    'uoregon': 'University of Oregon',
    'upenn': 'University of Pennsylvania',
    'uq': 'The University of Queensland',
    'usc': 'University of Southern California',
    'usf': 'University of South Florida',
    'usg': 'University System of Georgia',
    'usu': 'Utah State University',
    'usupress': 'Utah State University Press',
    'uta': 'University of Texas at Arlington',
    'utah': 'University of Utah',
    'utdallas': 'University of Texas at Dallas',
    'utep': 'University of Texas at El Paso',
    'utexas': 'University of Texas at Austin',
    'uth': 'University of Texas Health Science Center at Houston',
    'utk': 'University of Tennessee, Knoxville',
    'utoronto': 'University of Toronto',
    'utsa': 'University of Texas at San Antonio',
    'uuhhs': 'Unitarian Universalist History and Heritage Society',
    'uvm': 'University of Vermont',
    'uwf': 'University of West Florida',
    'uwyo': 'University of Wyoming',
    'vanderbilt': 'Vanderbilt University',
    'vcu': 'Virginia Commonwealth University',
    'virginia': 'University of Virginia',
    'vt': 'Virginia Tech',
    'washington': 'University of Washington',
    'wayne': 'Wayne State University',
    'wesleyan': 'Wesleyan University',
    'wfu': 'Wake Forest University',
    'whitman': 'Whitman College',
    'wichita': 'Wichita State University',
    'williams': 'Williams College',
    'wisc': 'University of Wisconsin - Madison',
    'wsu': 'Washington State University',
    'wustl': 'Washington University in St. Louis',
    'wvu': 'West Virginia University',
    'yale': 'Yale University'
}
